version: 2
updates:
  # Enable daily version updates for pip
  - package-ecosystem: "pip"
    # limit to security updates only
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "daily"

  # Enable weekly version updates for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable weekly version updates for devcontainer
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/"
    schedule:
      interval: "weekly"
