apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: dataflow-mqtt-endpoint
  namespace: azure-iot-operations
spec:
  endpointType: mqtt
  mqttSettings:
    host: "aio-mq-dmqtt-frontend:1883"
    tls:
      mode: Enabled
    clientIdPrefix: "client-id-prefix"
    keepAliveSeconds: 12
    maxInflightMessages: 100
    protocol: "WebSockets"
    qos: 1
    retain: Keep
    sessionExpirySeconds: 3600
  authentication:
    method: X509Credentials
    x509CredentialsSettings:
      secretRef: "aio-ca-key-pair-test-only"