name: Release

on:
  workflow_call:
    inputs:
      update_index:
        type: boolean
        description: 'Push this version to the extension index'
        default: false

jobs:
  release:
    environment: production
    runs-on: [self-hosted, 1ES.Pool=iotupx-github-hosted-pool, 1ES.ImageOverride=MMSUbuntu20.04]
    steps:
      - name: Download Wheel
        uses: actions/download-artifact@v3
        with:
          name: azure-edge-cli-ext
          path: ./release
      - name: Setup python
        uses: actions/setup-python@v3
        with:
            python-version: "3.9"
      - name: Install and determine version
        run: |
          wheel=$(find ./release/*.whl)
          pip install $wheel
          version=$(pip show azure_edge | grep Version: | awk '{print $2}')
          echo "wheel=$wheel" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV
          echo "tag=v$version" >> $GITHUB_ENV
      - name: Download SBOM
        uses: actions/download-artifact@v3
        with:
          name: SBOM
          path: ./release/SBOM
      - name: Zip SBOM
        run: zip ./SBOM.zip ./release/SBOM -r
      - name: Create Release
        run: |
          echo tag: "${{ env.tag }}"
          echo version: "${{ env.version }}"
          echo wheel: "${{ env.wheel }}"
          gh release create "${{ env.tag }}" --generate-notes -d -t "azure-edge ${{ env.version }}" "${{ env.wheel }}" "./SBOM.zip#SBOM" --repo "${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  index_update:
    needs: [release]
    if: ${{ github.event.inputs.update_index == 'true' }}
    uses: ./.github/workflows/actions/update_private_index.yml
    secrets: inherit