name: "[auto] Simple Build"
permissions: {}
on:
  workflow_call:
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v7
        with:
            python-version: "3.13"
      - name: Build Wheel
        run: |
          pip install -r dev_requirements.txt
          python -m build
      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v7
        with:
          path: dist/*.whl
          name: azure-iot-ops-cli-ext