name: Integration tests
run-name: "Integration tests [${{ inputs.test-scenarios != '' && inputs.test-scenarios || 'all' }}]"
on:
  schedule:
    - cron: "0 9 * * *" # Run daily at 1:00 AM Pacific Time (9:00 AM UTC)
  workflow_call:
    inputs:
      resource-group:
        description: Resource group for cluster creation
        type: string
        required: true
        default: ops-cli-int-test-rg
      test-scenarios:
        description: "Run specific scenarios (comma-separated list)"
        type: string
        required: false
        default: ""
      runtime-init-args:
        description: Additional INIT arguments (beyond cluster name, resource group, schema registry).
        type: string
        required: false
        default: ""
      runtime-create-args:
        description: Additional CREATE arguments (beyond cluster name, resource group, instance name).
        type: string
        required: false
        default: ""
      custom-locations-oid:
        description: Custom Locations OID
        type: string
        required: false
        default: "51dfe1e8-70c6-4de5-a08e-e18aff23d815"
      init-continue-on-error:
        description: Continue on error for init integration tests
        type: boolean
        required: false
        default: true
      keep-on-failure:
        description: Number of minutes to keep the cluster(s) active on failure (max 240 min).
        type: number
        required: false
        default: 0
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
  workflow_dispatch:
    inputs:
      resource-group:
        description: Resource group for cluster creation
        type: string
        required: true
        default: ops-cli-int-test-rg
      test-scenarios:
        description: "Run specific scenarios (comma-separated list)"
        type: string
        required: false
        default: ""
      custom-locations-oid:
        description: Object ID of Custom Locations RP
        type: string
        required: false
        default: "51dfe1e8-70c6-4de5-a08e-e18aff23d815"
      runtime-init-args:
        description: Additional INIT arguments (beyond cluster name, resource group, schema registry).
        type: string
        required: false
        default: ""
      runtime-create-args:
        description: Additional CREATE arguments (beyond cluster name, resource group, instance name).
        type: string
        required: false
        default: ""
      init-continue-on-error:
        description: Continue on error for init integration tests
        type: boolean
        required: false
        default: true
      keep-on-failure:
        description: Number of minutes to keep the cluster(s) active on failure (max 240 min).
        type: number
        required: false
        default: 0

permissions:
  # required for OpenID federation
  contents: "read"
  id-token: "write"

env:
  RESOURCE_GROUP: "${{ inputs.resource-group || 'ops-cli-int-test-rg' }}"
  K3S_VERSION: "v1.31.1+k3s1"
  CUSTOM_LOCATIONS_OID: "${{ inputs.custom-locations-oid || '51dfe1e8-70c6-4de5-a08e-e18aff23d815' }}"
  KEEP_ALIVE: ${{ inputs.keep-on-failure || 0 }}
  RUNTIME_CREATE_ARGS: "${{ inputs.runtime-create-args }}"
  RUNTIME_INIT_ARGS: "${{ inputs.runtime-init-args }}"
  TEST_SCENARIOS: "${{ inputs.test-scenarios || '' }}"

jobs:
  setup:
    name: "Check Inputs"
    runs-on: ubuntu-latest
    # Run on dispatch, or ensure scheduled runs only on dev branch
    if: github.event_name != 'schedule' || (github.repository == 'azure/azure-iot-ops-cli-extension' && github.ref == 'refs/heads/dev')
    outputs:
      runtime_create_args: ${{ steps.runtime_args.outputs.CREATE_ARGS }}
      runtime_init_args: ${{ steps.runtime_args.outputs.INIT_ARGS }}
    steps:
      - name: "Check Keep On Failure arg"
        run: |
          if [[ ! ${{ env.KEEP_ALIVE }} =~ ^[0-9]+$ ]]; then
            echo "The keep alive input is not a valid number"
            exit 1
          fi
      - name: "Output runtime args for int-test job"
        id: runtime_args
        run: |
          echo "CREATE_ARGS=${{ env.RUNTIME_CREATE_ARGS }}" >> $GITHUB_OUTPUT
          echo "INIT_ARGS=${{ env.RUNTIME_INIT_ARGS }}" >> $GITHUB_OUTPUT

  build-matrix:
    name: "Build Test Matrix"
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: "Checkout for config"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: "Build matrix from scenarios"
        id: matrix
        uses: ./.github/actions/build-int-test-matrix
        with:
          test-scenarios: ${{ env.TEST_SCENARIOS }}

  unit-test:
    name: "Run linter and unit tests"
    # Ensure matrix build succeeded before running any tests
    needs: build-matrix
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v4
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: "Setup test suite"
        run: |
          python -m pip install tox
          tox r -vv --notest
      - name: "Run test suite"
        run: tox r --skip-pkg-install
      - name: "Upload coverage report"
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: ./.coverage
          include-hidden-files: true
  int-test:
    needs: [setup, build-matrix]
    if: ${{ success() && needs.build-matrix.outputs.matrix != '[]' }}
    env:
      CLUSTER_NAME: "opt${{ github.run_number }}${{ matrix.scenario.name }}"
      INSTANCE_NAME: "inst${{ github.run_number }}${{ matrix.scenario.name }}"
      KEYVAULT_NAME: "kv${{ github.run_number }}"
      INIT_ARG: ""
      CREATE_ARG: ""
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    name: "${{ matrix.scenario.description }}"
    runs-on: ubuntu-24.04
    steps:
      - name: "Export init args and environment variables"
        run: |
          echo "INIT_ARG=${{ matrix.scenario.init_args }} ${{ env.RUNTIME_INIT_ARGS }}" >> $GITHUB_ENV
          echo "CREATE_ARG=${{ matrix.scenario.create_args }} ${{ env.RUNTIME_CREATE_ARGS }}" >> $GITHUB_ENV

          env_json='${{ toJson(matrix.scenario.env) }}'
          if [[ "$env_json" != "null" && "$env_json" != "[]" ]]; then
            echo "$env_json" | jq -r '.[] | "\(.name)=\(.value)"' >> $GITHUB_ENV
          fi
      - name: "Output variables for future steps"
        id: "env_out"
        run: |
          echo "RESOURCE_GROUP=${{ env.RESOURCE_GROUP }}" >> $GITHUB_OUTPUT
          echo "CLUSTER_NAME=${{ env.CLUSTER_NAME }}" >> $GITHUB_OUTPUT
          echo "INSTANCE_NAME=${{ env.INSTANCE_NAME }}" >> $GITHUB_OUTPUT
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: "Checkout extension source for build"
        uses: actions/checkout@v4
      - name: "Build and install local IoT Ops extension from source"
        run: |
          pip install -r dev_requirements.txt
          python -m build
          wheel=$(find ./dist/*.whl)
          az extension add --source $wheel -y
      - name: "Create k3s cluster"
        uses: ./.github/actions/create-k3s-cluster
      - name: "Apply custom cluster issuer"
        if: ${{ matrix.scenario.needs_trust || contains(env.INIT_ARG, '--user-trust') }}
        uses: ./.github/actions/setup-trust-bundle
      - name: "Tox test environment setup for init"
        run: |
          python -m pip install tox
          tox r -vv -e python-init-int --notest
          if [[ -n "${{ matrix.scenario.tox_env }}" ]]; then
            tox r -vv -e "${{ matrix.scenario.tox_env }}" --notest
          fi
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "ARC connect cluster"
        uses: ./.github/actions/connect-arc
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          custom-locations-oid: ${{ env.CUSTOM_LOCATIONS_OID }}
          enable-workload-identity: ${{ matrix.scenario.needs_trust && 'true' || 'false' }}
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: "Setup Cluster Resources"
        id: "init_reqs"
        uses: ./.github/actions/setup-cluster-resources
        with:
          suffix: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - name: "OIDC Token exchange service"
        run: |
          while true; do
            token_request=$ACTIONS_ID_TOKEN_REQUEST_TOKEN
            token_uri=$ACTIONS_ID_TOKEN_REQUEST_URL
            token=$(curl -H "Authorization: bearer $token_request" "${token_uri}&audience=api://AzureADTokenExchange" | jq .value -r)
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -t ${{ secrets.AZURE_TENANT_ID }} --federated-token $token --output none
            # Sleep for 4 minutes
            sleep 240
          done &
      - name: "Tox INIT Integration Tests"
        env:
          azext_edge_init_continue_on_error: ${{ inputs.init-continue-on-error || '' }}
          azext_edge_rg: ${{ steps.env_out.outputs.RESOURCE_GROUP }}
          azext_edge_cluster: ${{ steps.env_out.outputs.CLUSTER_NAME }}
          azext_edge_instance: ${{ steps.env_out.outputs.INSTANCE_NAME }}
          azext_edge_init_args: ${{ matrix.scenario.init_args }} ${{ needs.setup.outputs.runtime_init_args }}
          azext_edge_create_args: ${{ matrix.scenario.create_args }} ${{ needs.setup.outputs.runtime_create_args }}
          azext_edge_schema_registry_id: ${{ steps.init_reqs.outputs.SCHEMA_REGISTRY_ID }}
          azext_edge_adr_namespace_id: ${{ steps.init_reqs.outputs.ADR_NAMESPACE_ID }}
        run: |
          tox r -e python-init-int --skip-pkg-install
          tox r -e report
      - name: "${{ matrix.scenario.description }}"
        if: ${{ matrix.scenario.tox_env != '' }}
        env:
          azext_edge_rg: ${{ steps.env_out.outputs.RESOURCE_GROUP }}
          azext_edge_cluster: ${{ steps.env_out.outputs.CLUSTER_NAME }}
          azext_edge_instance: ${{ steps.env_out.outputs.INSTANCE_NAME }}
          azext_edge_sp_object_id: ${{ secrets.AZURE_CLIENT_ID }}
        run: |
          PYTEST_ARGS=""
          if [[ "${{ matrix.scenario.parallel }}" == "true" ]]; then
            PYTEST_ARGS="--dist=loadfile -n auto"
          fi
          tox r -e "${{ matrix.scenario.tox_env }}" --skip-pkg-install -- $PYTEST_ARGS
          tox r -e report
      - name: "Upload coverage artifacts"
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.scenario.name }}
          path: ./.coverage
          include-hidden-files: true
      - name: "Run smoke tests"
        continue-on-error: true
        run: |
          az iot ops support create-bundle
          az iot ops support create-bundle --svc broker --broker-traces
          az iot ops support create-bundle --ops-service acs secretstore
          az iot ops check
          az iot ops check --pre
          az iot ops check --post
          az iot ops check --as-object
          az iot ops check --svc broker --resources broker brokerlistener
          az iot ops asset query -g ${{ env.RESOURCE_GROUP }} --location westus -o table
          az iot ops get-versions --inline
      - name: "Keep cluster alive"
        if: ${{ env.KEEP_ALIVE > 0 && failure() }}
        run: |
          kubectl create clusterrolebinding teamaccessbinding --clusterrole cluster-admin --group ${{ secrets.CLUSTER_ACCESS_SG }} >/dev/null 2>&1

          echo "Cluster ${{ env.CLUSTER_NAME }} in resource group ${{ env.RESOURCE_GROUP }}"
          echo "Instance name ${{ env.INSTANCE_NAME }}"
          echo ""

          echo "Please ensure you have the required roles: \"Azure Arc Kubernetes Viewer\" and \"Azure Arc Enabled Kubernetes Cluster User Role\""
          echo "To connect to the cluster please use"
          echo "az connectedk8s proxy -g ${{ env.RESOURCE_GROUP }} -n ${{ env.CLUSTER_NAME }}"
          echo ""

          TIME_LIMIT=${{ env.KEEP_ALIVE }}
          if (( $TIME_LIMIT > 240 )); then
            echo "Given time limit is over the maximum of 4 hours. Setting to 4 hours."
            TIME_LIMIT=240
          fi

          for ((i=0; i < $TIME_LIMIT; i+=1)); do
            if [ $(( i % 10 )) == 0 ]; then
              echo "Remaining time: $(( $TIME_LIMIT - i )) minutes"
            fi
            sleep 60s
          done
      - name: "Delete Cluster for redeployment"
        if: ${{ matrix.scenario.test_redeploy }}
        timeout-minutes: 30
        run: |
          az iot ops delete -n ${{ env.INSTANCE_NAME }} -g ${{ env.RESOURCE_GROUP }} -y
      - name: "Redeploy cluster via tox"
        if: ${{ matrix.scenario.test_redeploy }}
        env:
          azext_edge_rg: ${{ steps.env_out.outputs.RESOURCE_GROUP }}
          azext_edge_cluster: ${{ steps.env_out.outputs.CLUSTER_NAME }}
          azext_edge_instance: ${{ steps.env_out.outputs.INSTANCE_NAME }}
          azext_edge_init_args: ${{ matrix.scenario.init_args }} ${{ needs.setup.outputs.runtime_init_args }}
          azext_edge_create_args: ${{ matrix.scenario.create_args }} ${{ needs.setup.outputs.runtime_create_args }}
          azext_edge_schema_registry_id: ${{ steps.init_reqs.outputs.SCHEMA_REGISTRY_ID }}
          azext_edge_adr_namespace_id: ${{ steps.init_reqs.outputs.ADR_NAMESPACE_ID }}
        run: |
          tox r -e python-init-int --skip-pkg-install
      - name: "Delete AIO resources"
        if: ${{ always() }}
        run: |
          az iot ops delete --cluster ${{ env.CLUSTER_NAME }} -g ${{ env.RESOURCE_GROUP }} -y --force
      - name: "Delete connected cluster and resources"
        if: ${{ always() }}
        run: |
          az resource delete -v --name ${{ env.CLUSTER_NAME }} -g ${{ env.RESOURCE_GROUP }} --resource-type Microsoft.Kubernetes/connectedClusters --verbose
          if [ "${{ steps.init_reqs.outputs.SCHEMA_REGISTRY_ID }}" ]; then
            az resource delete -v --id ${{ steps.init_reqs.outputs.SCHEMA_REGISTRY_ID }} --verbose
          else
            echo "No schema registry to delete"
          fi
          if [ "${{ steps.init_reqs.outputs.ADR_NAMESPACE_ID }}" ]; then
            az resource delete -v --id ${{ steps.init_reqs.outputs.ADR_NAMESPACE_ID }} --verbose
          else
            echo "No ADR namespace to delete"
          fi
          if [ "${{ steps.init_reqs.outputs.STORAGE_ID }}" ]; then
            az resource delete -v --id ${{ steps.init_reqs.outputs.STORAGE_ID }} --verbose
          else
            echo "No storage account to delete"
          fi
  combine-coverage:
    name: "Combine coverage reports"
    if: ${{ always() }}
    needs: [unit-test, int-test]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v4
      - name: "Download all coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: ./coverage_parts
      - name: "Combine coverage and generate report"
        run: |
          pip install coverage
          coverage combine ./coverage_parts/*/.coverage
          coverage report
          coverage html --directory ./htmlcov --title "AIO CLI Combined Coverage Report"
      - name: "Upload combined coverage artifact"
        uses: actions/upload-artifact@v4
        with:
          name: combined-coverage
          path: ./htmlcov
