name: Build and Publish Release
on:
  # only manual trigger
  workflow_dispatch:
jobs:
  security:
    uses: ./.github/workflows/security_checks.yml
  test:
    uses: ./.github/workflows/tox.yml
  build:
    uses: ./.github/workflows/build.yml
  linter:
    needs: [build]
    uses: ./.github/workflows/azdev_linter.yml
  release:
    needs: [build, linter, security, test]
    uses: ./.github/workflows/stage_release.yml